version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'MSSQL_SA_PASSWORD=1StrongPwd!!'
      MSSQL_PID: 'Express'