  version: '3'
  services:
    mssql:
      image: mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
      ports:
        - 1433:1433
      environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'MSSQL(!)OnDocker'
        MSSQL_PID: 'Express'