name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ASPNETCORE_ENVIRONMENT
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $GITHUB_WORKSPACE/ET.WebAPI/ET.WebAPI.Api/Dockerfile --tag dotnet-api:$(date +%s)
      
    - name: Start SqlServer
      uses: 280780363/sqlserver-action@v1.0
      with:
        accept eula: true
        sa password: test
        
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        ApiDb: "Server=localhost;Uid=sa;Password=test;Persist Security Info=True;"
