name: .NET Unit and Integration Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: Development
      GITHUB_WORKFLOW_CONNECTION_STRING: "Data Source=localhost;Uid=sa;Password=test;Persist Security Info=True;"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Run MsSQL server 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - uses: addnab/docker-run-action@v3
      with:
        username: sa
        password: test
        registry: mcr.microsoft.com/mssql
        image: server:2019-latest
        options: -v ${{ github.workspace }}:/work -e ABC=123
        run: |
          echo "Running Script"
          /work/run-script
        
    - name: Test
      run: dotnet test --no-build --verbosity normal
